FROM apache/hive:3.1.3

USER root
RUN apt-get update && apt-get install -y wget curl \
    && rm -rf /var/lib/apt/lists/*
# Download required AWS JAR files into /opt/hive/lib
RUN curl -L -o /opt/hive/lib/hadoop-aws-3.1.2.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.1.2/hadoop-aws-3.1.2.jar && \
    curl -L -o /opt/hive/lib/aws-java-sdk-bundle-1.11.375.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.375/aws-java-sdk-bundle-1.11.375.jar && \
    ls -lh /opt/hive/lib/hadoop-aws-3.1.2.jar /opt/hive/lib/aws-java-sdk-bundle-1.11.375.jar